### ISSUE TITLE
.fai and .dict naming conventions

### ISSUE THREAD

**Issue by deanpettinga** [vari-bbc/prep_bbc_shared#3]
I'm running GATK4's SplitNCigarReads in the Broad best practice workflow for [RNAseq short variant calling](https://gatk.broadinstitute.org/hc/en-us/articles/360035531192-RNAseq-short-variant-discovery-SNPs-Indels-).

when i supply the reference fasta here: `prep_bbc_shared/data/mm10_gencode/sequence.fa`, SplitNCigarReads expects the following naming conventions within `mm10_gencode/`:

- `sequence.fa`
- `sequence.fai`
- `sequence.dict`

in contrast to the current naming convention:
- `sequence.fa`
- `sequence.fa.fai`
- `sequence.fa.dict`

I think the easiest and most harmless fix would be to add the following symlinks to the shell directive command in `rule fai_and_dict:` such that both conventions are present in `mm10_gencode/`:
- `mm10_gencode.dict -> mm10_gencode.fa.dict`
- `mm10_gencode.fai -> mm10_gencode.fa.fai`

Is there any reason why this would be ill-advised? seems like a simple fix, just wanted to double-check...

-Dean

**Comment by genomics-kl** [comment]
Thanks for catching this. I would prefer to just change the rule to produce it with the correct suffix to minimize clutter. I think support for GATK is one of the main reasons for using these files. Input files and the software versions will remain the same, so it should produce the exact same file as what you have used, but you can make a copy of it now to be safe if you want.

Did you get an error message that you could share here? According to a post on GATK (https://gatk.broadinstitute.org/hc/en-us/articles/360035531652-FASTA-Reference-genome-format), the expected format should be `sequence.dict` and `sequence.fasta.fai` (I think `.fasta.fai` should work also).

**Comment by genomics-kl** [comment]
Would be cool if you could re-run your script after we make this change to make sure it works for GATK tools. Let's talk on Teams tomorrow.
